INSERT INTO team07.oferta (nazwa_wycieczki, rodzaj_wycieczki,  kierunek, liczba_dni, cena_za_jedna_osobe, atrakcje, miejsce_zameldowania, wyzywienie, miasto, opis, koszt_organizacji_za_jedna_osobe) 
VALUES
    ('Nurkowanie w Malezji', 'Przygodowa', 'Malezja', 5, 9000, 'Wieczór disco', 'Hotel', 'Wliczone w cenę', 'Sipadan', 'Eksploracja podwodnego świata w jednym z najlepszych miejsc nurkowych.', 7435.25),
    ('Rejs po greckich wyspach', 'Wypoczynkowa', 'Grecja', 14, 8000, 'DJ Stasix na pokładzie', 'Jacht', 'We własnym zakresie', '', 'Luksusowy rejs z wieczornymi imprezami na pokładzie.', 7100.75),
    ('Safari w Afryce', 'Przygodowa', 'Kenia', 7, 12000, 'Safari jeepem', 'Lodge', 'Wliczone w cenę', 'Nairobi', 'Niezapomniane safari wśród dzikich zwierząt w afrykańskim buszu.', 10234.10),
    ('Zorza polarna w Laponii', 'Przygodowa', 'Finlandia', 5, 7000, 'Wyprawa na skuterach śnieżnych', 'Domek z balią', 'Wliczone w cenę', 'Rovaniemi', 'Magiczne noce pod zorzami polarnymi.', 6843.50),
    ('Zwiedzanie zamków Szkocji', 'Kulturowa', 'Szkocja', 10, 6000, 'Wieczór z dudziarzem', 'Zamek', 'We własnym zakresie', 'Edynburg', 'Historyczna podróż przez najsłynniejsze zamki i tradycje Szkocji.', 5300.00),
    ('Podróż wzdłuż Amazonki', 'Ekspedycja', 'Brazylia', 14, 15000, 'Spływ łodzią', 'Ośrodek w dżungli', 'Wliczone w cenę', 'Manaus', 'Eksploracja amazońskiej dżungli pełna emocji.', 12580.30),
    ('Hunger Games: Wersja Grzybobranie', 'Przygodowa', 'Polska', 7, 5000, 'Zbieranie grzybów w błocie, grzybowe potyczki, grzybowy tor przeszkód', 'Domek w lesie', 'We własnym zakresie', 'Białowieża', 'Ekstremalna wycieczka, w której lasy zamieniają się w pole bitwy, a zamiast walki na śmierć i życie – walczysz o grzyby. W tej niecodziennej wersji igrzysk śmierci, każdy uczestnik zostaje wprowadzony do Grzybowego Królestwa z misją – znaleźć jak najwięcej najcenniejszych grzybów w okolicy.', 2700),
    ('Zaginiony Skarb Królowej Bałtyku', 'Przygodowa', 'Polska', 5, 4000, 'Poszukiwanie wskazówek na plażach, nurkowanie po skrzynie skarbów, piracka uczta na pokładzie', 'Statek', 'Wliczone w cenę', 'Gdańsk', 'Poszukiwanie ukrytego skarbu podczas rejsu statkiem na wodach Bałtyku.', 3900.00),
    ('Lato w Wiosce Hobbitów', 'Tematyczna', 'Polska', 3, 2500, 'Pieczenie lembasów, quiz wiedzy o Śródziemiu, warsztaty tworzenia pierścieni', 'Wioska Hobbitów', 'We własnym zakresie', 'Zielona Góra', 'Weekend w stylu Władcy Pierścieni, gdzie uczestnicy żyją jak hobbici w specjalnej wiosce.', 2357.50),
    ('Sylwester ze Skolimem', 'Rozrywkowa', 'Polska', 1, 3000, 'Ekskluzywny koncert Skolima, karaoke z jego hitami, konkurs tańca disco, fajerwerki północne', 'Sala balowa', 'Wliczone w cenę', 'Warszawa', 'Wyjątkowy sylwester w rytmie disco polo z koncertem Skolima i niezapomnianą zabawą do rana.', 1720.70)